Controllers/AsistanController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PediatriNobetYonetimSistemi.Data;
using PediatriNobetYonetimSistemi.Models;

namespace PediatriNobetYonetimSistemi.Controllers
{
    public class AsistanController : Controller
    {
        private readonly DatabaseContext _context;

        public AsistanController(DatabaseContext context)
        {
            _context = context;
        }

        [AllowAnonymous] // Hoca listesini herkes görebilir
        public async Task<IActionResult> Index()
        {
            var asistanlar = await _context.Asistan.Include(h => h.Departman).ToListAsync();
            return View(asistanlar);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["DepartmanId"] = new SelectList(_context.Departman, "DepartmanId", "DepartmanAdi");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Ad, Soyad, Mail, DepartmanId")] Asistan asistan)
        {

            ViewData["DepartmanId"] = new SelectList(_context.Departman, "DepartmanId", "DepartmanAdi", asistan.DepartmanId);

            _context.Add(asistan);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var asistan = await _context.Asistan.FindAsync(id);
            if (asistan == null) return NotFound();

            ViewData["DepartmanId"] = new SelectList(_context.Departman, "DepartmanId", "DepartmanAdi", asistan.DepartmanId);
            return View(asistan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Ad, Soyad, Mail, DepartmanId")] Asistan asistan)
        {
            if (id != asistan.Id) return NotFound();


            _context.Update(asistan);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var asistan = await _context.Asistan.Include(h => h.Departman)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asistan == null) return NotFound();

            return View(asistan);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asistan = await _context.Asistan.FindAsync(id);
            if (asistan != null)
            {
                _context.Asistan.Remove(asistan);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> KullaniciAsistanlari()
        {
            var asistanlar = await _context.Asistan
                                           .Include(a => a.Departman)
                                           .ToListAsync();

            return View(asistanlar);
        }
    }
}

Controllers/HocaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PediatriNobetYonetimSistemi.Data;
using PediatriNobetYonetimSistemi.Models;

namespace PediatriNobetYonetimSistemi.Controllers
{
    public class HocaController : Controller
    {
        private readonly DatabaseContext _context;

        public HocaController(DatabaseContext context)
        {
            _context = context;
        }

        [AllowAnonymous] 
        public async Task<IActionResult> Index()
        {
            var hocalar = await _context.Hoca.Include(h => h.Departman).ToListAsync();
            return View(hocalar);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["DepartmanId"] = new SelectList(_context.Departman, "DepartmanId", "DepartmanAdi");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Ad, Soyad, Mail, DepartmanId")] Hoca hoca)
        {
           
            ViewData["DepartmanId"] = new SelectList(_context.Departman, "DepartmanId", "DepartmanAdi", hoca.DepartmanId);
                
            _context.Add(hoca);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var hoca = await _context.Hoca.FindAsync(id);
            if (hoca == null) return NotFound();

            ViewData["DepartmanId"] = new SelectList(_context.Departman, "DepartmanId", "DepartmanAdi", hoca.DepartmanId);
            return View(hoca);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Ad, Soyad, Mail, DepartmanId")] Hoca hoca)
        {
            if (id != hoca.Id) return NotFound();

            
                _context.Update(hoca);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var hoca = await _context.Hoca.Include(h => h.Departman)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hoca == null) return NotFound();

            return View(hoca);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hoca = await _context.Hoca.FindAsync(id);
            if (hoca != null)
            {
                _context.Hoca.Remove(hoca);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> KullaniciHocalari()
        {
            var hocalar = await _context.Hoca.Include(h => h.Departman).ToListAsync();
            return View(hocalar);
        }
    }
}

Controllers/NobetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PediatriNobetYonetimSistemi.Data;
using PediatriNobetYonetimSistemi.Models;

namespace PediatriNobetYonetimSistemi.Controllers
{
    public class NobetController : Controller
    {
        private readonly DatabaseContext _context;

        public NobetController(DatabaseContext context)
        {
            _context = context;
        }

        [AllowAnonymous] 
        public async Task<IActionResult> Index()
        {
            var nobetler = await _context.Nobet
                .Include(n => n.Asistan)            // Asistan bilgisi
                    .ThenInclude(a => a.Departman)  // Asistan'ın Departmanı
                .Include(n => n.Departman)          // Nöbetin ait olduğu Departman
                .ToListAsync();

            return View(nobetler);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["AsistanId"] = new SelectList(
                _context.Asistan
                    .Include(a => a.Departman)
                    .Select(a => new
                    {
                        a.Id,
                        Text = $"{a.Departman.DepartmanAdi} - {a.Ad} {a.Soyad}"
                    }),
                "Id", "Text");
            ViewData["DepartmanId"] = new SelectList(_context.Departman, "DepartmanId", "DepartmanAdi");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("AsistanId, DepartmanId, BaslamaTarihi, BaslamaSaati, BitisTarihi, BitisSaati")] Nobet nobet)
        {
            
                _context.Add(nobet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var nobet = await _context.Nobet.FindAsync(id);
            if (nobet == null) return NotFound();

            ViewData["AsistanId"] = new SelectList(
                _context.Asistan
                    .Include(a => a.Departman)
                    .Select(a => new
                    {
                        a.Id,
                        Text = $"{a.Departman.DepartmanAdi} - {a.Ad} {a.Soyad}"
                    }),
                "Id", "Text", nobet.AsistanId);
            ViewData["DepartmanId"] = new SelectList(_context.Departman, "DepartmanId", "DepartmanAdi", nobet.DepartmanId);
            return View(nobet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id, AsistanId, DepartmanId, BaslamaTarihi, BaslamaSaati, BitisTarihi, BitisSaati")] Nobet nobet)
        {
            if (id != nobet.Id) return NotFound();

           
                    _context.Update(nobet);
                    await _context.SaveChangesAsync();
                
               
                return RedirectToAction(nameof(Index));
            
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var nobet = await _context.Nobet
                .Include(n => n.Asistan)
                .Include(n => n.Departman)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nobet == null) return NotFound();

            return View(nobet);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nobet = await _context.Nobet.FindAsync(id);
            if (nobet != null)
            {
                _context.Nobet.Remove(nobet);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/RandevuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PediatriNobetYonetimSistemi.Data;
using PediatriNobetYonetimSistemi.Models;

namespace PediatriNobetYonetimSistemi.Controllers
{
    public class RandevuController : Controller
    {
        private readonly DatabaseContext _context;

        public RandevuController(DatabaseContext context)
        {
            _context = context;
        }

        [AllowAnonymous] 
        public IActionResult Index()
        {
            var randevular = _context.Randevu
                .Include(r => r.Hoca)
                .ThenInclude(h => h.Departman)
                .Include(r => r.Asistan)
                .ThenInclude(a => a.Departman)
                .ToList();

            return View(randevular);
        }

        
        [AllowAnonymous]
        public IActionResult Create()
        {
            ViewData["HocaId"] = new SelectList(_context.Hoca
                .Select(h => new
                {
                    HocaId = h.Id,
                    Text = $"{h.Departman.DepartmanAdi} - {h.Ad} {h.Soyad}"
                }),
                "HocaId", "Text");

            ViewData["AsistanId"] = new SelectList(_context.Asistan
                .Select(a => new
                {
                    AsistanId = a.Id,
                    Text = $"{a.Departman.DepartmanAdi} - {a.Ad} {a.Soyad}"
                }),
                "AsistanId", "Text");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create([Bind("Tarih, HocaId, AsistanId")] Randevu randevu)
        {
                _context.Add(randevu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var randevu = await _context.Randevu.Include(r => r.Hoca).Include(r => r.Asistan).FirstOrDefaultAsync(r => r.Id == id);
            if (randevu == null) return NotFound();

            ViewData["HocaId"] = new SelectList(_context.Hoca
                .Include(h => h.Departman)  // Departman bilgisini almak için Include kullanıyoruz
                .Select(h => new { h.Id, Name = $"{h.Departman.DepartmanAdi} - {h.Ad} {h.Soyad}" }), "Id", "Name", randevu.HocaId);

            ViewData["AsistanId"] = new SelectList(_context.Asistan
                .Include(a => a.Departman)  
                .Select(a => new { a.Id, Name = $"{a.Departman.DepartmanAdi} - {a.Ad} {a.Soyad}" }), "Id", "Name", randevu.AsistanId);

            return View(randevu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Tarih, HocaId, AsistanId")] Randevu randevu)
        {
            if (id != randevu.Id) return NotFound();

                    _context.Update(randevu);
                    await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
           
        }

        [AllowAnonymous]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var randevu = await _context.Randevu.Include(r => r.Hoca).Include(r => r.Asistan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (randevu == null) return NotFound();

            return View(randevu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var randevu = await _context.Randevu.FindAsync(id);
            if (randevu != null)
            {
                _context.Randevu.Remove(randevu);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin Paneli";
}

<div class="container text-center">
    <h1 class="display-4">Admin Paneli</h1>
    <p class="lead">Lütfen yönetmek istediğiniz kategoriyi seçin:</p>
    <div class="row justify-content-center">
        <div class="col-md-4 mb-5">
            <div class="card admin-panel-card">
                <div class="card-body">
                    <h5 class="card-title">Asistan Yönetimi</h5>
                    <div class="text-area-container">
                        <p>Kadromuzdaki asistanlarımızı ve bilgilerini görüntüleyebilir, gerekli düzeltmeleri yapabilirsiniz.</p>
                    </div>
                    <a class="btn btn-primary mt-3" asp-controller="Asistan" asp-action="Index">Yönet</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card admin-panel-card">
                <div class="card-body">
                    <h5 class="card-title">Departman Yönetimi</h5>
                    <div class="text-area-container">
                        <p>Hastanemizin departmanlarını, tanıtımlarını ve yatak sayılarını uygun gördüğünüz şekilde düzenleyebilirsiniz.</p>
                    </div>
                    <a class="btn btn-primary mt-3" asp-controller="Departman" asp-action="Index">Yönet</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card admin-panel-card">
                <div class="card-body">
                    <h5 class="card-title">Hoca Yönetimi</h5>
                    <div class="text-area-container">
                        <p>Kadromuzdaki hocalarımızı ve bilgilerini görüntüleyebilir, gerekli düzeltmeleri yapabilirsiniz.</p>
                    </div>
                    <a class="btn btn-primary mt-3" asp-controller="Hoca" asp-action="Index">Yönet</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card admin-panel-card">
                <div class="card-body">
                    <h5 class="card-title">Randevu Yönetimi</h5>
                    <div class="text-area-container">
                        <p>Yardıma ihtiyaç duyan asistanlarımız ve buluşmak istedikleri hocalarımız için gün ve saat belirleyebilirsiniz.</p>
                    </div>
                    <a class="btn btn-primary mt-3" asp-controller="Randevu" asp-action="Index">Yönet</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card admin-panel-card">
                <div class="card-body">
                    <h5 class="card-title">Nöbet Yönetimi</h5>
                    <div class="text-area-container">
                        <p>Nöbet tutulması gerekilen departmanları belirleyebilir, asistanlarımızı yönlendirebilirsiniz.</p>
                    </div>
                    <a class="btn btn-primary mt-3" asp-controller="Nobet" asp-action="Index">Yönet</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card admin-panel-card">
                <div class="card-body">
                    <h5 class="card-title">Acil Durum Yönetimi</h5>
                    <div class="text-area-container">
                        <p>Karşılaşılan acil durumları kaydedebilir, gerekirse bütün sağlık çalışanı ekibimize bildirim gönderebilirsiniz.</p>
                    </div>
                    <a class="btn btn-primary mt-3" asp-controller="AcilDurum" asp-action="Acil">Yönet</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card admin-panel-card">
                <div class="card-body">
                    <h5 class="card-title">Hoca Müsaitlik Yönetimi</h5>
                    <div class="text-area-container">
                        <p>Hocalarımızın programlarını ve boş vakitlerini buradan düzenleyebilirsiniz.</p>
                    </div>
                    <a class="btn btn-primary mt-3" asp-controller="HocaMusaitlik" asp-action="Index">Yönet</a>
                </div>
            </div>
        </div>
    </div>
</div>